---
title: "Analysis and Visualisation"
output: html_notebook
---

```{r}
# Libraries
library(usethis)
library(ggplot2)
library(readr)
library(maps)
library(tidytext)
library(dplyr)


```

# Load extracted data 
```{r}
# Sentiment Analysis
afinn_news24 <- read_rds("Data/Final_Data/afinn_news24.rds")
news24_score <- read_rds("Data/Final_Data/news24_score.rds")
afinn_TimesLIVE <- read_rds("Data/Final_Data/afinn_TimesLIVE.rds")
TimesLIVE_score <- read_rds("Data/Final_Data/TimesLIVE_score.rds")
afinn_eNCA <- read_rds("Data/Final_Data/afinn_eNCA.rds")
eNCA_score <- read_rds("Data/Final_Data/eNCA_score.rds")
afinn_IOL <- read_rds("Data/Final_Data/afinn_IOL.rds")
IOL_score <- read_rds("Data/Final_Data/IOL_score.rds")
afinn_ewn <- read_rds("Data/Final_Data/afinn_ewn.rds")
ewn_score <- read_rds("Data/Final_Data/ewn_score.rds")
afinn_SABCNews <- read_rds("Data/Final_Data/afinn_SABCNews.rds")
SABC_score <- read_rds("Data/Final_Data/SABC_score.rds")


#Load Topic Modelling Data
#LDA
News24_top_terms_LDA <- read_rds("Data/Final_Data/News24_top_terms_LDA.rds")
TimesLIVE_top_terms_LDA <- read_rds("Data/Final_Data/timesLIVE_top_terms_LDA.rds")
ewn_top_terms_LDA <- read_rds("Data/Final_Data/Ewnupdate_top_terms_LDA.rds")
IOL_top_terms_LDA <- read_rds("Data/Final_Data/IOL_top_terms_LDA.rds")
eNCA_top_terms_LDA <- read_rds("Data/Final_Data/eNCA_top_terms_LDA.rds")
SABC_top_terms_LDA <- read_rds("Data/Final_Data/SABC_top_terms_LDA.rds")
global_top_terms_LDA <- read_rds("Data/Final_Data/global_top_terms_LDA.rds")

#STM
News24_top_terms <- read_rds("Data/Final_Data/News24_top_terms.rds")
TimesLIVE_top_terms <- read_rds("Data/Final_Data/timesLIVE_top_terms.rds")
ewnupdate_top_terms <- read_rds("Data/Final_Data/Ewnupdate_top_terms.rds")
IOL_top_terms <- read_rds("Data/Final_Data/IOL_top_terms.rds")
eNCA_top_terms <- read_rds("Data/Final_Data/eNCA_top_terms.rds")
SABC_top_terms <- read_rds("Data/Final_Data/SABC_top_terms.rds")
global_top_terms <- read_rds("Data/Final_Data/global_top_terms.rds")

# Additional Analysis
Frequency_tweets <- read_rds("Data/Final_Data/Frequency_tweets.rds")
retweet_tweets <- read_rds("Data/Final_Data/retweet_tweets.rds")
Likes_tweets <- read_rds("Data/Final_Data/Like_tweets.rds")
Type_data <- read_rds("Data/Final_Data/Tweet_Type.rds")
```


# Generating visuals
## Global Theme
```{r}
t <- theme(
  axis.text.x=element_text(colour = "black",face = "bold"),
  axis.text.y=element_text(colour = "black",face = "bold"),
  axis.title.x=element_blank(),
  axis.title.y=element_blank(),
  axis.ticks=element_blank(),
  panel.border=element_blank(),
  panel.grid.major.y =element_blank(),
  panel.grid.major.x =element_line(colour = "black"), 
  panel.grid.minor=element_blank(),
  plot.background=element_rect(fill = "grey"),
  plot.caption = element_text(colour ="black",face = "bold" ,hjust = 1),
  plot.title = element_text(size = 20, colour ="black",face = "bold" ,hjust = 0.5),
)

```


## Sentiment visuals
```{r}
# Sentiment's theme
sentiment_theme <- theme(
  axis.text.x=element_text(colour = "black",face = "bold"),
  axis.text.y=element_text(colour = "black",face = "bold"),
  axis.title.x=element_blank(),
  axis.title.y=element_blank(),
  panel.border=element_blank(),
  panel.grid.major=element_line(colour = "grey"),
  panel.grid.major.x=element_blank(), 
  panel.grid.minor=element_blank(),
  plot.background=element_rect(fill = "grey"),
  plot.caption = element_text(colour ="black",face = "bold" ,hjust = +1),
  strip.text = element_text(face = "bold"),
  plot.title = element_text(size = 20, colour ="black",face = "bold" ,hjust = 0.5),
)

# sentiment analysis
# performed wit following topics "covid|corona|covid 19|covid19|coronavirus|sars cov 2|sars cov"

# News24
news24_plot <- afinn_news24 %>% top_n(10) %>% mutate(word = reorder(word,n)) %>% ggplot(aes(x= word, y = n)) + geom_col(color = "black", fill = "red") + coord_flip() + sentiment_theme %+replace% theme(panel.grid.major=element_blank()) + labs(x = NULL, y = NULL, title = "News24 Frequently Used Words", subtitle = "Top 10", caption = "\nSource: Data collected from Twitter's REST API via rtweet")
news24_plot 

ggplot(news24_score, aes(x=value,y=count)) + geom_bar(stat = "identity", color = "black", fill = "red") + sentiment_theme + scale_x_continuous(breaks = c(-5,-4,-3,-2,-1,0,1,2,3,4,5)) + expand_limits(x = c(-5,5)) +   labs(x = NULL, y = NULL, title = "News24 Sentiment Score", caption = "\nSource: Data collected from Twitter's REST API via rtweet")

# TimesLIVE
TimesLIVE_plot <- afinn_TimesLIVE %>% top_n(10) %>% head(10) %>% mutate(word = reorder(word,n)) %>% ggplot(aes(x= word, y = n)) + geom_col(color = "black", fill = "red") + coord_flip() + sentiment_theme %+replace% theme(panel.grid.major=element_blank()) + labs(x = NULL, y = NULL, title = "TimesLIVE Frequently Used Words", subtitle = "Top 10", caption = "\nSource: Data collected from Twitter's REST API via rtweet")
TimesLIVE_plot 

ggplot(TimesLIVE_score, aes(x=value,y=count)) + geom_bar(stat = "identity", color = "black", fill = "red") + sentiment_theme + scale_x_continuous(breaks = c(-5,-4,-3,-2,-1,0,1,2,3,4,5)) + expand_limits(x = c(-5,5)) + labs(x = NULL, y = NULL, title = "TimesLIVE Sentiment Score", caption = "\nSource: Data collected from Twitter's REST API via rtweet")

# eNCA
eNCA_plot <- afinn_eNCA %>% top_n(10) %>% mutate(word = reorder(word,n)) %>% head(10) %>% ggplot(aes(x= word, y = n)) + geom_col(color = "black", fill = "red") + coord_flip() + sentiment_theme %+replace% theme(panel.grid.major=element_blank()) + labs(x = NULL, y = NULL, title = "eNCA Frequently Used Words", subtitle = "Top 10", caption = "\nSource: Data collected from Twitter's REST API via rtweet")
eNCA_plot 

ggplot(eNCA_score, aes(x=value,y=count)) + geom_bar(stat = "identity", color = "black", fill = "red") + sentiment_theme + scale_x_continuous(breaks = c(-5,-4,-3,-2,-1,0,1,2,3,4,5)) + expand_limits(x = c(-5,5)) + labs(x = NULL, y = NULL, title = "eNCA Sentiment Score", caption = "\nSource: Data collected from Twitter's REST API via rtweet")

# IOL
IOL_plot <- afinn_IOL %>% top_n(10) %>% mutate(word = reorder(word,n)) %>% head(10) %>% ggplot(aes(x= word, y = n)) + geom_col(color = "black", fill = "red") + coord_flip() + sentiment_theme %+replace% theme(panel.grid.major=element_blank()) + labs(x = NULL, y = NULL, title = "IOL Frequently Used Words", subtitle = "Top 10", caption = "\nSource: Data collected from Twitter's REST API via rtweet")
IOL_plot 

ggplot(IOL_score, aes(x=value,y=count)) + geom_bar(stat = "identity", color = "black", fill = "red") + sentiment_theme + scale_x_continuous(breaks = c(-5,-4,-3,-2,-1,0,1,2,3,4,5)) + expand_limits(x = c(-5,5)) + labs(x = NULL, y = NULL, title = "IOL Sentiment Score", caption = "\nSource: Data collected from Twitter's REST API via rtweet")

# ewnupdate
ewn_plot <- afinn_ewn %>% top_n(10) %>% mutate(word = reorder(word,n)) %>% head(10) %>% ggplot(aes(x= word, y = n)) + geom_col(color = "black", fill = "red") + coord_flip() + sentiment_theme %+replace% theme(panel.grid.major=element_blank()) + labs(x = NULL, y = NULL, title = "EWN Frequently Used Words", subtitle = "Top 10", caption = "\nSource: Data collected from Twitter's REST API via rtweet")
ewn_plot 

ggplot(ewn_score, aes(x=value,y=count)) + geom_bar(stat = "identity", color = "black", fill = "red") + sentiment_theme + scale_x_continuous(breaks = c(-5,-4,-3,-2,-1,0,1,2,3,4,5)) + expand_limits(x = c(-5,5)) + labs(x = NULL, y = NULL, title = "EWN Sentiment Score", caption = "\nSource: Data collected from Twitter's REST API via rtweet")

# SABCNEWS
SABC_plot <- afinn_SABCNews %>% top_n(10) %>% mutate(word = reorder(word,n)) %>% head(10) %>% ggplot(aes(x= word, y = n)) + geom_col(color = "black", fill = "red") + coord_flip() + sentiment_theme %+replace% theme(panel.grid.major=element_blank()) + labs(x = NULL, y = NULL, title = "SABCNews Frequently Used Words", subtitle = "Top 10", caption = "\nSource: Data collected from Twitter's REST API via rtweet")
SABC_plot 

ggplot(SABC_score, aes(x=value,y=count)) + geom_bar(stat = "identity", color = "black", fill = "red") + sentiment_theme + scale_x_continuous(breaks = c(-5,-4,-3,-2,-1,0,1,2,3,4,5)) + expand_limits(x = c(-5,5)) + labs(x = NULL, y = NULL, title = "SABCNews Sentiment Score", caption = "\nSource: Data collected from Twitter's REST API via rtweet")


```


## Topic Modelling visuals
###  Latent Dirichlet Allocation 

```{r}
News24_top_terms_LDA %>%
  mutate(term = reorder(term, beta)) %>%
  ggplot(aes(term, beta, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  scale_y_continuous(breaks = c(0.00, 0.005, 0.010, 0.015, 0.02),labels = c("0", ".05", ".01", ".015", ".02")) +
  expand_limits(y=c(0,0.02)) +
  facet_wrap(~ topic, scales = "free") +
  coord_flip() +
  labs(title = "LDA Topic Modeling for News24 ", caption = "\nSource: Data collected from Twitter's REST API via rtweet"
) + t %+replace% theme(
  strip.text = element_text(face = "bold"),
  axis.text.y=element_text(colour = "black",face = "bold", size = 7),
  axis.text.x=element_text(colour = "black",face = "bold", size = 7),
)

```

```{r}
#Scale not applied due to plot 12 having a significant outlier

TimesLIVE_top_terms_LDA %>%
  mutate(term = reorder(term, beta)) %>%
  ggplot(aes(term, beta, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  #scale_y_continuous(breaks = c(0.00, 0.005, 0.015,0.05,0.45),labels = c("0", ".05",".15",".5",".45")) +
  #expand_limits(y=c(0,0.025)) +
  facet_wrap(~ topic, scales = "free") +
  coord_flip() +
  labs(title = "LDA Topic Modeling for TimesLive ", caption = "\nSource: Data collected from Twitter's REST API via rtweet"
) + t %+replace% theme(
  strip.text = element_text(face = "bold"),
  axis.text.y=element_text(colour = "black",face = "bold", size = 7),
  axis.text.x=element_text(colour = "black",face = "bold", size = 7),
)
```


```{r}
ewn_top_terms_LDA %>%
  mutate(term = reorder(term, beta)) %>%
  ggplot(aes(term, beta, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  scale_y_continuous(breaks = c(0.00, 0.005, 0.015,0.05),labels = c("0", ".05",".15",".5")) +
  expand_limits(y=c(0,0.015)) +
  facet_wrap(~ topic, scales = "free") +
  coord_flip() +
  labs(title = "LDA Topic Modeling for EWN ", caption = "\nSource: Data collected from Twitter's REST API via rtweet"
) + t %+replace% theme(
  strip.text = element_text(face = "bold"),
  axis.text.y=element_text(colour = "black",face = "bold", size = 7),
  axis.text.x=element_text(colour = "black",face = "bold", size = 7),
)
```


```{r}
IOL_top_terms_LDA %>%
  mutate(term = reorder(term, beta)) %>%
  ggplot(aes(term, beta, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  scale_y_continuous(breaks = c(0.00, 0.005, 0.010, 0.015, 0.02),labels = c("0", ".05", ".01", ".015", ".02")) +
  expand_limits(y=c(0,0.015)) +
  facet_wrap(~ topic, scales = "free") +
  coord_flip() +
  labs(title = "LDA Topic Modeling for IOL ", caption = "\nSource: Data collected from Twitter's REST API via rtweet"
) + t %+replace% theme(
  strip.text = element_text(face = "bold"),
  axis.text.y=element_text(colour = "black",face = "bold", size = 7),
  axis.text.x=element_text(colour = "black",face = "bold", size = 7),
)
```

```{r}
eNCA_top_terms_LDA %>%
  mutate(term = reorder(term, beta)) %>%
  ggplot(aes(term, beta, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  scale_y_continuous(breaks = c(0.00, 0.005, 0.010, 0.015, 0.02),labels = c("0", ".05", ".01", ".015", ".02")) +
  expand_limits(y=c(0,0.02)) +
  facet_wrap(~ topic, scales = "free") +
  coord_flip() +
  labs(title = "LDA Topic Modeling for eNCA ", caption = "\nSource: Data collected from Twitter's REST API via rtweet"
) + t %+replace% theme(
  strip.text = element_text(face = "bold"),
  axis.text.y=element_text(colour = "black",face = "bold", size = 7),
  axis.text.x=element_text(colour = "black",face = "bold", size = 7),
)
```

```{r}
SABC_top_terms_LDA %>%
  mutate(term = reorder(term, beta)) %>%
  ggplot(aes(term, beta, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  scale_y_continuous(breaks = c(0.00, 0.005, 0.010, 0.015, 0.02),labels = c("0", ".05", ".01", ".015", ".02")) +
  expand_limits(y=c(0,0.02)) +
  facet_wrap(~ topic, scales = "free") +
  coord_flip() +
  labs(title = "LDA Topic Modeling for SABCNews ", caption = "\nSource: Data collected from Twitter's REST API via rtweet"
) + t %+replace% theme(
  strip.text = element_text(face = "bold"),
  axis.text.y=element_text(colour = "black",face = "bold", size = 7),
  axis.text.x=element_text(colour = "black",face = "bold", size = 7),
)
```

```{r}
global_top_terms_LDA %>%
  mutate(term = reorder(term, beta)) %>%
  ggplot(aes(term, beta, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  scale_y_continuous(breaks = c(0.00, 0.005, 0.010, 0.015, 0.02),labels = c("0", ".05", ".01", ".015", ".02")) +
  expand_limits(y=c(0,0.02)) +
  facet_wrap(~ topic, scales = "free") +
  coord_flip() +
  labs(title = "LDA Topic Modeling for News24 ", caption = "\nSource: Data collected from Twitter's REST API via rtweet"
) + t %+replace% theme(
  strip.text = element_text(face = "bold"),
  axis.text.y=element_text(colour = "black",face = "bold", size = 7),
  axis.text.x=element_text(colour = "black",face = "bold", size = 7),
)

```


### Structural Topic Modelling

```{r}
#News24 STM Plot
News24_top_terms %>%
  mutate(term = reorder(term, beta)) %>%
  ggplot(aes(term, beta, fill = factor(topic))) +
  geom_col(show.legend = FALSE) + 
  scale_y_continuous(breaks = c(0.00, 0.02, 0.04, 0.060, 0.080),labels = c("0", ".02", ".04", ".06", ".08")) +
  expand_limits(y=c(0,0.08)) + 
  facet_wrap(~ topic, scales = "free") + 
  coord_flip() +
  labs(title = "Structural Topic Modeling for News24 ", caption = "\nSource: Data collected from Twitter's REST API via rtweet"
) + t %+replace% theme(
  strip.text = element_text(face = "bold"),
  axis.text.y=element_text(colour = "black",face = "bold", size = 7),
  axis.text.x=element_text(colour = "black",face = "bold", size = 7),
  )
```

```{r}
#TimesLIVE STM Plot
TimesLIVE_top_terms %>%
  mutate(term = reorder(term, beta)) %>%
  ggplot(aes(term, beta, fill = factor(topic))) +
  geom_col(show.legend = FALSE) + 
  scale_y_continuous(breaks = c(0.00, 0.02, 0.04, 0.060, 0.080),labels = c("0", ".02", ".04", ".06", ".08")) +
  expand_limits(y=c(0,0.08)) + 
  facet_wrap(~ topic, scales = "free") + 
  coord_flip() +
  labs(title = "Structural Topic Modeling for TimesLIVE ", caption = "\nSource: Data collected from Twitter's REST API via rtweet"
) + t %+replace% theme(
  strip.text = element_text(face = "bold"),
  axis.text.y=element_text(colour = "black",face = "bold", size = 7),
  axis.text.x=element_text(colour = "black",face = "bold", size = 7),
  )
```


```{r}
#ewn STM Plot
ewnupdate_top_terms %>%
  mutate(term = reorder(term, beta)) %>%
  ggplot(aes(term, beta, fill = factor(topic))) +
  geom_col(show.legend = FALSE) + 
  scale_y_continuous(breaks = c(0.00, 0.02, 0.04, 0.060, 0.080),labels = c("0", ".02", ".04", ".06", ".08")) +
  expand_limits(y=c(0,0.08)) + 
  facet_wrap(~ topic, scales = "free") + 
  coord_flip() +
  labs(title = "Structural Topic Modeling for EWN ", caption = "\nSource: Data collected from Twitter's REST API via rtweet"
) + t %+replace% theme(
  strip.text = element_text(face = "bold"),
  axis.text.y=element_text(colour = "black",face = "bold", size = 7),
  axis.text.x=element_text(colour = "black",face = "bold", size = 7),
  )
```


```{r}
#IOL STM Plot
IOL_top_terms %>%
  mutate(term = reorder(term, beta)) %>%
  ggplot(aes(term, beta, fill = factor(topic))) +
  geom_col(show.legend = FALSE) + 
  scale_y_continuous(breaks = c(0.00, 0.02, 0.04, 0.060, 0.080),labels = c("0", ".02", ".04", ".06", ".08")) +
  expand_limits(y=c(0,0.08)) + 
  facet_wrap(~ topic, scales = "free") + 
  coord_flip() +
  labs(title = "Structural Topic Modeling for IOL ", caption = "\nSource: Data collected from Twitter's REST API via rtweet"
) + t %+replace% theme(
  strip.text = element_text(face = "bold"),
  axis.text.y=element_text(colour = "black",face = "bold", size = 7),
  axis.text.x=element_text(colour = "black",face = "bold", size = 7),
  )
```


```{r}
#eNCA STM Plot
eNCA_top_terms %>%
  mutate(term = reorder(term, beta)) %>%
  ggplot(aes(term, beta, fill = factor(topic))) +
  geom_col(show.legend = FALSE) + 
  scale_y_continuous(breaks = c(0.00, 0.02, 0.04, 0.060, 0.080),labels = c("0", ".02", ".04", ".06", ".08")) +
  expand_limits(y=c(0,0.08)) + 
  facet_wrap(~ topic, scales = "free") + 
  coord_flip() +
  labs(title = "Structural Topic Modeling for eNCA ", caption = "\nSource: Data collected from Twitter's REST API via rtweet"
) + t %+replace% theme(
  strip.text = element_text(face = "bold"),
  axis.text.y=element_text(colour = "black",face = "bold", size = 7),
  axis.text.x=element_text(colour = "black",face = "bold", size = 7),
  )
```


```{r}
#SABC STM Plot
SABC_top_terms %>%
  mutate(term = reorder(term, beta)) %>%
  ggplot(aes(term, beta, fill = factor(topic))) +
  geom_col(show.legend = FALSE) + 
  scale_y_continuous(breaks = c(0.00, 0.02, 0.04, 0.060, 0.080),labels = c("0", ".02", ".04", ".06", ".08")) +
  expand_limits(y=c(0,0.08)) + 
  facet_wrap(~ topic, scales = "free") + 
  coord_flip() +
  labs(title = "Structural Topic Modeling for SABC ", caption = "\nSource: Data collected from Twitter's REST API via rtweet"
) + t %+replace% theme(
  strip.text = element_text(face = "bold"),
  axis.text.y=element_text(colour = "black",face = "bold", size = 7),
  axis.text.x=element_text(colour = "black",face = "bold", size = 7),
  )
```

```{r}
#Global STM Plot
global_top_terms %>%
  mutate(term = reorder(term, beta)) %>%
  ggplot(aes(term, beta, fill = factor(topic))) +
  geom_col(show.legend = FALSE) + 
  scale_y_continuous(breaks = c(0.00, 0.02, 0.04, 0.060, 0.080),labels = c("0", ".02", ".04", ".06", ".08")) +
  expand_limits(y=c(0,0.08)) + 
  facet_wrap(~ topic, scales = "free") + 
  coord_flip() +
  labs(title = "Structural Topic Modeling for News24 ", caption = "\nSource: Data collected from Twitter's REST API via rtweet"
) + t %+replace% theme(
  strip.text = element_text(face = "bold"),
  axis.text.y=element_text(colour = "black",face = "bold", size = 7),
  axis.text.x=element_text(colour = "black",face = "bold", size = 7),
  )
```

# Additional Analysis
```{r}
# Additional's theme
Other_theme <- theme(
  axis.text.x=element_text(colour = "black",face = "bold"),
  axis.text.y=element_text(colour = "black",face = "bold"),
  axis.title.x=element_blank(),
  axis.title.y=element_blank(),
  panel.border=element_blank(),
  panel.grid.major=element_line(colour = "grey"),
  panel.grid.major.x=element_blank(), 
  panel.grid.minor=element_blank(),
  plot.background=element_rect(fill = "grey"),
  plot.caption = element_text(colour ="black",face = "bold" ,hjust = +1),
  strip.text = element_text(face = "bold"),
  plot.title = element_text(size = 20, colour ="black",face = "bold" ,hjust = 0.5),
)


#frequency of tweets
ggplot(Frequency_tweets, aes(x = date, y = News24)) + Other_theme + geom_line(color = "black", size = 0.9) + geom_line(aes(x = date, y = timesLIVE), color = "blue", size = 0.9) + geom_line(aes(x = date, y = Ewnupdate), color = "red", size = 0.9) + geom_line(aes(x = date, y = IOL), color = "brown", size = 0.9) + geom_line(aes(x = date, y = eNCA), color = "green", size = 0.9) + geom_line(aes(x = date, y = SABC), color = "yellow", size = 0.9) + scale_x_date(breaks = "1 day",date_labels = "%d") + scale_y_continuous(breaks = seq(0, 160, by = 20)) + labs(x = NULL, y = NULL, title = "Frequency of Tweets", subtitle = "Three week period in June", caption = "\nSource: Data collected from Twitter's REST API via rtweet")


#retweet Count
ggplot(retweet_tweets, aes(x = date, y = News24)) + Other_theme + geom_line(color = "black", size = 0.9) + geom_line(aes(x = date, y = timesLIVE), color = "blue", size = 0.9) + geom_line(aes(x = date, y = Ewnupdate), color = "red", size = 0.9) + geom_line(aes(x = date, y = IOL), color = "brown", size = 0.9) + geom_line(aes(x = date, y = eNCA), color = "green", size = 0.9) + geom_line(aes(x = date, y = SABC), color = "yellow", size = 0.9) + scale_x_date(breaks = "1 day",date_labels = "%d")+ scale_y_continuous(trans = "log2", breaks = c(250,500,750,1000,2000,4000,6000,8000)) + labs(x = NULL, y = NULL, title = "Retweet count", subtitle = "Three week period in June", caption = "\nSource: Data collected from Twitter's REST API via rtweet")


#Like Count
ggplot(Likes_tweets, aes(x = date, y = News24)) + Other_theme + geom_line(color = "black", size = 0.9) + geom_line(aes(x = date, y = timesLIVE), color = "blue", size = 0.9) + geom_line(aes(x = date, y = Ewnupdate), color = "red", size = 0.9) + geom_line(aes(x = date, y = IOL), color = "brown", size = 0.9) + geom_line(aes(x = date, y = eNCA), color = "green", size = 0.9) + geom_line(aes(x = date, y = SABC), color = "yellow", size = 0.9) + scale_x_date(breaks = "1 day",date_labels = "%d") + scale_y_continuous(breaks = seq(0, 20000, by = 1500)) + labs(x = NULL, y = NULL, title = "Like counter", subtitle = "Three week period in June", caption = "\nSource: Data collected from Twitter's REST API via rtweet")


#covid vs non covid tweets
ggplot(Type_data, aes(x="", y=tweet_count, fill = tweet_type)) + geom_bar(stat = "identity", width = 1)+ coord_polar(theta="y", start = 0) + geom_text(aes(label = paste0(round(tweet_count/8901*100), "%")), position = position_stack(vjust=0.5)) + theme_void() %+replace% theme(plot.caption = element_text(colour ="black",hjust = -1),) + labs(x = NULL, y = NULL, fill = NULL, title = "Comparison of Covid Coverage by News Media", caption = "\nSource: Data collected from Twitter's REST API via rtweet")


```

