---
title: "Data Extraction"
output: html_notebook
---

```{r message=FALSE, warning=FALSE, include=FALSE}
#install_github("mkearney/rtweet")

#Packages
library(usethis)
library(devtools)
library(rtweet)
library(readr)
library(topicmodels)
library(maps)
```


```{r eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}

#Define credentials
app_name<-""
consumer_key<-""
consumer_secret<-""
access_token<-""
access_token_secret<-""


```

## checking rate limits
```{r}
# see rate limits
# The rate limit for the standard search API is 18,000 tweets per fifteen minutes. With a bearer token, the rate limit is 45,000 tweets per fifteen minutes. 
rate_limits<-rate_limit()
head(rate_limits[,1:4])
```


```{r}
#
#create_token(app=app_name,
#             consumer_key=consumer_key, consumer_secret=consumer_secret,
#             access_token = access_token, access_secret = access_token_secret)

```


## Searching for tweets...
### Collect first batch of tweets
```{r echo=TRUE, message=TRUE, warning=TRUE}
#PULL FINAL VERSION ON MONDAY OR TUESDAY
News24_tweets <- get_timelines(c("News24"), n = 3200, include_rts=FALSE)
TimesLIVE_tweets <- get_timelines(c("TimesLIVE"), n = 3200, include_rts=FALSE)
eNCA_tweets <- get_timelines(c("eNCA"), n = 3200, include_rts=FALSE)

```


### Collect second batch of tweets
```{r echo=TRUE, message=TRUE, warning=TRUE}
IOL_tweets <- get_timelines(c("IOL"), n=3200, include_rts=FALSE)
SABCNews_tweets <- get_timelines(c("SABCNews"), n=3200, include_rts=FALSE)
ewnupdates_tweets <- get_timelines(c("ewnupdates"), n=3200, include_rts=FALSE)
```

### Collecting additional tweets
```{r}
SAgovnews_tweets <- get_timelines(c("SAgovnews"), n=3200, include_rts=FALSE)
SowetanLIVE_tweets <- get_timelines(c("SowetanLIVE"), n=3200, include_rts=FALSE)
City_Press_tweets <- get_timelines(c("City_Press"), n=3200, include_rts=FALSE)
mailandguardian_tweets <- get_timelines(c("mailandguardian"), n=3200, include_rts=FALSE)
```


### Collect third batch of tweets
```{r echo=TRUE, message=FALSE, warning=FALSE}
#Not useful
#trend_tweets <- get_trends("South Africa")
#trend_tweets
```

### Collect fourth batch of tweets
```{r}
#Define terms to search by
q1 <- "Covid OR Corona OR Covid-19 OR Covid19 OR Coronavirus OR SARS-CoV-2 OR SARS-CoV"
q2 <- "OR #Covid OR #Corona OR #Covid-19 OR #Covid19 OR #Coronavirus OR #SARS-CoV-2 OR #SARS-CoV"
q <- paste(q1,q2)
```


```{r}
#UPDATE DAILY
#Collecting tweets for South Africa
tweets_za_19 <- search_tweets(q,geocode = lookup_coords("South Africa"), since="2020-06-19", until="2020-06-20", type="recent", include_rts=FALSE, n=18000)

#Collecting tweets for largest city in each province
tweets_bloem_19 <- search_tweets(q,geocode = lookup_coords("Bloemfontein"), since="2020-06-19", until="2020-06-20", type="recent", include_rts=FALSE, n=18000)
tweets_cpt_19 <- search_tweets(q,geocode = lookup_coords("Cape Town"), since="2020-06-19", until="2020-06-20", type="recent", include_rts=FALSE, n=18000)
tweets_durb_19 <- search_tweets(q,geocode = lookup_coords("Durban"), since="2020-06-19", until="2020-06-20", type="recent", include_rts=FALSE, n=18000)
tweets_jhb_19 <- search_tweets(q,geocode = lookup_coords("Johannesburg"), since="2020-06-19", until="2020-06-20", type="recent", include_rts=FALSE, n=18000)
tweets_kim_19 <- search_tweets(q,geocode = lookup_coords("Kimberley"), since="2020-06-19", until="2020-06-20", type="recent", include_rts=FALSE, n=18000)
tweets_klerk_19 <- search_tweets(q,geocode = lookup_coords("Klerksdorp"), since="2020-06-19", until="2020-06-20", type="recent", include_rts=FALSE, n=18000)
tweets_mbomb_19 <- search_tweets(q,geocode = lookup_coords("Mbombela"), since="2020-06-19", until="2020-06-20", type="recent", include_rts=FALSE, n=18000)
tweets_polo_19 <- search_tweets(q,geocode = lookup_coords("Polokwane"), since="2020-06-19", until="2020-06-20", type="recent", include_rts=FALSE, n=18000)
tweets_pe_19 <- search_tweets(q,geocode = lookup_coords("Port Elizabeth"), since="2020-06-19", until="2020-06-20", type="recent", include_rts=FALSE, n=18000)
```

```{r}
#Retrieve profiles
News24_profile <- lookup_users("News24")
TimesLIVE_profile <- lookup_users("TimesLIVE")
eNCA_profile <- lookup_users("eNCA")
IOL_profile <- lookup_users("IOL")
SABCNews_profile <- lookup_users("SABCNews")
ewnupdates_profile <- lookup_users("ewnupdates")

#Get Followers count
News24_followers <- News24_profile$followers_count
TimesLIVE_followers <- TimesLIVE_profile$followers_count
eNCA_followers <- eNCA_profile$followers_count
IOL_followers <- IOL_profile$followers_count
SABCNews_followers <- SABCNews_profile$followers_count
ewnupdates_followrtd <- ewnupdates_profile$followers_count

#Get Friends count
News24_followers <- News24_profile$friends_count
TimesLIVE_followers <- TimesLIVE_profile$friends_count
eNCA_followers <- eNCA_profile$friends_count
IOL_followers <- IOL_profile$friends_count
SABCNews_followers <- SABCNews_profile$friends_count
ewnupdates_followers <- ewnupdates_profile$friends_count
```

## finished collecting tweets!


# Exporting Tweets to .rds
```{r}
#UPDATE DAILY
#Export Filtered Data for 19/06/2020
write_rds(tweets_za_19, "Data/Raw_Filtered_Data/tweets_za_19.rds")
write_rds(tweets_bloem_19, "Data/Raw_Filtered_Data/tweets_bloem_19.rds")
write_rds(tweets_cpt_19, "Data/Raw_Filtered_Data/tweets_cpt_19.rds")
write_rds(tweets_durb_19, "Data/Raw_Filtered_Data/tweets_durb_19.rds")
write_rds(tweets_jhb_19, "Data/Raw_Filtered_Data/tweets_jhb_19.rds")
write_rds(tweets_kim_19, "Data/Raw_Filtered_Data/tweets_kim_19.rds")
write_rds(tweets_klerk_19, "Data/Raw_Filtered_Data/tweets_klerk_19.rds")
write_rds(tweets_mbomb_19, "Data/Raw_Filtered_Data/tweets_mbomb_19.rds")
write_rds(tweets_polo_19, "Data/Raw_Filtered_Data/tweets_polo_19.rds")
write_rds(tweets_pe_19, "Data/Raw_Filtered_Data/tweets_pe_19.rds")

```


```{r echo=TRUE}
# Exporting Timeline Data
write_rds(News24_tweets, "Data/Raw_Timeline_Data/News24_tweets.rds")
write_rds(TimesLIVE_tweets, "Data/Raw_Timeline_Data/TimesLIVE_tweets.rds")
write_rds(eNCA_tweets, "Data/Raw_Timeline_Data/eNCA_tweets.rds")
write_rds(IOL_tweets,"Data/Raw_Timeline_Data/IOL_tweets.rds")
write_rds(SABCNews_tweets,"Data/Raw_Timeline_Data/SABCNews_tweets.rds")
write_rds(ewnupdates_tweets,"Data/Raw_Timeline_Data/ewnupdates_tweets.rds")
write_rds(SAgovnews_tweets,"Data/Raw_Timeline_Data/SAgovnews.rds")
write_rds(SowetanLIVE_tweets,"Data/Raw_Timeline_Data/SowetanLIVE.rds")
write_rds(City_Press_tweets,"Data/Raw_Timeline_Data/City_Press.rds")
write_rds(mailandguardian_tweets,"Data/Raw_Timeline_Data/mailandguardian.rds")
```

```{r}
#Exporting followers and following counts

```

